export interface Mission {
  id: number; animal: string; icon: string; habitat: string; place: string; region: string
  color: string; focus: string; tip: string; brief: string; fact: string; words: string[]; sentences: string[]
  mechanic: string; challenge: string
}

// Species featured in Animal Planet's Extinct or Alive (2018–2019) and its Shark Week specials.
export const source = 'https://en.wikipedia.org/wiki/Extinct_or_Alive#Episodes'
export const missions: Mission[] = [
  { id: 1, animal: 'Miller’s langur', icon: '🐒', habitat: 'Rainforest', place: 'Samarinda', region: 'Indonesia', color: '#547d53', focus: 'A → D · first steps', tip: 'Find the bumps on F and J. Rest your fingers on the home row, then reach gently for each key.', brief: 'Hey Henry! A rare langur is hiding in the forests of Borneo. Let’s follow the clues and keep it safe.', fact: 'Miller’s langur is a rare monkey from Borneo. Forrest filmed it for Extinct or Alive.', words: ['a', 'bad', 'dad', 'cab', 'lab', 'cap', 'cat', 'map', 'man', 'cut'], sentences: ['A cat can nap.', 'The map is in my bag.'], mechanic: 'Vine rescue', challenge: 'Cut the vines by spelling each word. Your machete can take four wrong keys.' },
  { id: 2, animal: 'Zanzibar leopard', icon: '🐆', habitat: 'Island forest', place: 'Stone Town', region: 'Tanzania', color: '#a87844', focus: 'E → H · longer words', tip: 'Reset on F and J between words. Stretch your fingers; keep your eyes on the screen.', brief: 'We’re off to Zanzibar! There may be a leopard in the island forest. Let’s look for signs without disturbing it.', fact: 'Forrest’s team recorded possible footage of a Zanzibar leopard; its identity remains unconfirmed.', words: ['lamp', 'hand', 'help', 'leaf', 'hide', 'game', 'plane', 'shade', 'forest'], sentences: ['Look for tracks near the trees.', 'The leopard may hide in the shade.'], mechanic: 'Camera traps', challenge: 'Type the clues to set up camera traps before the light fades.' },
  { id: 3, animal: 'Fernandina giant tortoise', icon: '🐢', habitat: 'Volcanic island', place: 'Puerto Ayora', region: 'Ecuador', color: '#718966', focus: 'I → L · steady rhythm', tip: 'Try the right-hand keys without lifting your whole hand. Return to home row after each reach.', brief: 'A giant tortoise has left tracks on a remote Galápagos island. Help the team follow them carefully!', fact: 'A female Fernandina giant tortoise was found on a 2019 expedition with Ecuadorian researchers and park rangers.', words: ['island', 'trail', 'shell', 'slow', 'stone', 'track', 'wild', 'little', 'turtle'], sentences: ['A tortoise walks along the trail.', 'We found tracks beside the rocks.'], mechanic: 'Trail markers', challenge: 'Use the mouse to check field markers, then type the trail notes.' },
  { id: 4, animal: 'Rio Apaporis caiman', icon: '🐊', habitat: 'River jungle', place: 'Leticia', region: 'Colombia', color: '#558b83', focus: 'M → P · both sides', tip: 'Both hands have a job. Keep them relaxed and let each finger travel from its home key.', brief: 'Time for a river expedition in Colombia! Help me scan the water for a very unusual caiman.', fact: 'Forrest’s team studied the Rio Apaporis caiman in Colombia; Colombian researchers had also documented it.', words: ['river', 'paddle', 'water', 'plant', 'camp', 'canoe', 'mud', 'deep', 'animal'], sentences: ['The river runs past the green trees.', 'A caiman waits beside the water.'], mechanic: 'River drone', challenge: 'Fly the drone with clue words and scan the riverbank.' },
  { id: 5, animal: 'Yangtze giant softshell turtle', icon: '🐢', habitat: 'Lake', place: 'Hanoi', region: 'Vietnam', color: '#688eaa', focus: 'Q → T · careful reaches', tip: 'The top row is a reach, not a new resting place. Come back to the home row.', brief: 'We’re headed to a lake in Vietnam. Every sighting of this giant turtle matters. Let’s collect careful observations!', fact: 'Forrest filmed a Yangtze giant softshell turtle at Dong Mo Lake with local conservation partners.', words: ['quiet', 'water', 'turtle', 'search', 'lake', 'gentle', 'watch', 'surface', 'protect'], sentences: ['A turtle comes up for air.', 'We watch the quiet lake at dawn.'], mechanic: 'Lake survey', challenge: 'Record observations and spot the markers by clicking them.' },
  { id: 6, animal: 'Saola', icon: '🦌', habitat: 'Mountain forest', place: 'Phong Nha', region: 'Vietnam', color: '#66816b', focus: 'U → Z · whole alphabet', tip: 'Notice which finger owns each key. Slow and correct beats fast and messy.', brief: 'The saola is so elusive it’s called the Asian unicorn. Let’s search the forest for clues, not chase the animal.', fact: 'Forrest searched for the saola in Vietnam on Extinct or Alive; a sighting was not confirmed.', words: ['saola', 'mountain', 'hidden', 'camera', 'footprint', 'wildlife', 'valley', 'explore'], sentences: ['The rare saola lives in the forest.', 'We check the camera near the mountain.'], mechanic: 'Mountain signals', challenge: 'Send signals from the forest lookout with precise typing.' },
  { id: 7, animal: 'Javan tiger', icon: '🐅', habitat: 'Tropical forest', place: 'Banyuwangi', region: 'Indonesia', color: '#bc7950', focus: 'Shift · capital letters', tip: 'Hold Shift with the opposite hand for capital letters. Let go before the next small letter.', brief: 'We’re exploring Java, where stories of a tiger still circulate. Help me map the route and record what we find.', fact: 'Forrest searched for the Javan tiger in Indonesia; its survival has not been established.', words: ['Java', 'Tiger', 'Trail', 'Forest', 'Clue', 'Watch', 'Track', 'Camera'], sentences: ['We look for clues in Java.', 'The team checks the forest trail.'], mechanic: 'Forest trail', challenge: 'Mark possible tracks and use Shift for the capital letters.' },
  { id: 8, animal: 'Pondicherry shark', icon: '🦈', habitat: 'Coastal ocean', place: 'Malé', region: 'Maldives', color: '#508ba0', focus: 'Numbers & punctuation', tip: 'Keep your hands anchored. Use Shift when you need a question mark or an exclamation mark.', brief: 'Let’s take our search to the ocean. Every detail in our notes could help identify a rare shark.', fact: 'Forrest investigated the Pondicherry shark in a Shark Week special; identification of a specimen remains debated.', words: ['reef', 'shark', 'ocean', 'fin', 'boat', 'wave', 'dive', '1 fish', '2 fins'], sentences: ['Is that a fin?', 'We saw 2 fins near the reef.'], mechanic: 'Reef sonar', challenge: 'Type the sonar readouts and look for a safe route.' },
  { id: 9, animal: 'Ivory-billed woodpecker', icon: '🐦', habitat: 'Swamp', place: 'Lafayette', region: 'United States', color: '#7b8758', focus: 'Tricky word patterns', tip: 'Read the whole word first, then type one letter at a time with the correct fingers.', brief: 'Let’s explore the Louisiana bayou. Listen for birds and record clues with care.', fact: 'Forrest searched for the ivory-billed woodpecker in Louisiana; its continued existence is disputed.', words: ['woodpecker', 'feather', 'branches', 'swamp', 'listen', 'nesting', 'habitat', 'binoculars'], sentences: ['A bird taps on a tall tree.', 'We listen and look for a feather.'], mechanic: 'Bayou lookout', challenge: 'Collect bird clues by typing and checking the lookout points.' },
  { id: 10, animal: 'Thylacine', icon: '🐺', habitat: 'Woodland', place: 'Hobart', region: 'Australia', color: '#8b745e', focus: 'Full sentences', tip: 'Read ahead, use both hands, and let accuracy lead the way. Your speed will follow.', brief: 'Our biggest mystery yet: the thylacine, also called the Tasmanian tiger. Let’s document what the forest tells us.', fact: 'Forrest searched for the thylacine in Tasmania; there is no confirmed living population.', words: ['Tasmania', 'thylacine', 'forest', 'research', 'wildlife', 'evidence', 'expedition'], sentences: ['The team walked through the quiet forest to look for clues.', 'We recorded each track and shared our notes with the local wildlife team.', 'A careful explorer protects animals and respects the places where they live.'], mechanic: 'Final expedition', challenge: 'Put all your typing skills together to complete the expedition journal.' },
]

export const testTexts = [
  'The small dog ran across the grass. A bird sat in a tree and sang a happy song. We went to the park after lunch. The sun was warm and the sky was blue. I saw a cat beside the gate. It looked at me and then went home.',
  'Today we took a walk by the lake. The water was calm and clear. My friend saw a duck near the shore. We sat on a bench and ate a snack. Then we went back home before the rain began.',
  'A little fox ran down the path. It stopped beside a log and looked around. The woods were quiet in the morning. I could hear the wind move the leaves. We watched from far away and let the fox go.',
]
